<?php

namespace Codersquad\Urlshortener\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlshortenerRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UrlshortenerRepository extends EntityRepository
{
}
